### ISSUE TITLE
Getting form name from GUID

### ISSUE THREAD

**Issue by HarveyWilliams** [umbraco/UmbracoFormsDocumentation#10]
Hi.

Is there some way that I can get an Umbraco forms name from its GUID?

Something like:

```
var form = Umbraco.Forms.Mvc.Library.GetForm(guid);

var formName = form.Name;
```

**Comment by warrenbuckley** [comment]
I would do something like this

```
using (var formStorage = new FormStorage())
{
    var form = formStorage.GetForm(guid);

    var formName = form.Name;
}
```

**Comment by HarveyWilliams** [comment]
@warrenbuckley Thanks for the quick reply.

I found that putting the GUID as a string into the `formStorage.GetForm()` method didn't work. Wrapping the GUID string in a `new Guid(guid)` and putting that into the `GetForm()` method worked.

My full code looks something like:

```
var records = Library.GetApprovedRecordsFromPage(umbracoPageNodeId).Items;

foreach (var record in records)
{
    using (var formStorage = new FormStorage())
    {
        // Form is null...
        var form = formStorage.GetForm(record.Form);

        // logic using form.Name...
    }
}
```

**Comment by warrenbuckley** [comment]
Yes sorry @HarveyWilliams I was not explicit it expects a proper GUID and not a string
Glad you got it sorted :)

**Comment by HarveyWilliams** [comment]
@warrenbuckley The method has an overload that allows for a string, but I guess this is for the name of the form, not the GUID in string format.

Thanks for the help again. :)
