### ISSUE TITLE
Major Issue in PostToUrl WorkflowType

### ISSUE THREAD

**Issue by georgeslegros** [umbraco/UmbracoFormsDocumentation#8]
Hello,

I know that this is definitely not the place to submit this but I guess you'll sort it out.

I discovered a major bug in PostToUrl. I used ILSpy to decompile the code and found this:

```
public override WorkflowExecutionStatus Execute(Record record, RecordEventArgs e)
		{
			[PIECE OF CODE THAT IS NOT RELEVANT]
			using (WebClient webClient = new WebClient())
			{
				NameValueCollection nameValueCollection = new NameValueCollection();
				if (list.Any<FieldMapping>())
				{
					[PIECE OF CODE THAT IS NOT RELEVANT]
					if (!string.IsNullOrEmpty(this.Password) && !string.IsNullOrEmpty(this.Username))
					{
						webClient.Credentials = new NetworkCredential(this.Username, this.Password);
					}
				}
				[PIECE OF CODE THAT IS NOT RELEVANT]
				webClient.UploadValues(this.Url, this.Method, nameValueCollection);
			}
			return 3;
		}
```

You guys are taking the credentials into account ONLY IF THERE ARE FIELDS MAPPING... Nonsense!!!

Now that I found it, I can work around the problem but I think it deserves a hotfix.

**Comment by warrenbuckley** [comment]
Hello @georgeslegros 
Rather than posting issue on the documentation issue tracker, I suggest you raise this on the Umbraco Issue Tracker and assigning it to the Umbraco Forms project - http://issues.umbraco.org/issues/CON

Many Thanks,
Warren

**Comment by georgeslegros** [comment]
Honestly and no offence but it took so long to figure out such a stupid mistake that I am not going to loose any more time creating an account on any other system.
I guess someone that cares about their product will bubble that information up to whoever can fix this.

**Comment by warrenbuckley** [comment]
Apologies you feel that way @georgeslegros I am more than happy to create the issue on your behalf but it would be much better for you to log it, so if there any further questions or discussions to be had it is made in the right place.

http://issues.umbraco.org/issue/CON-905
